name: Next Service Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      -'**/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
        
        
    - name: Deploy to server
      run : |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
              cd project/url-manager-fe
              git pull
              sudo docker compose build next --no-cache
              sudo docker compose up -d next
              sudo docker image prune -a -f
            EOF


